# Name of the workflow
name: Update Website

# Triggers on push to main branch
on:
  push:
    branches: [ main ]
    paths:
      - 'lib/version.py'
      - 'releases/website/**'
  workflow_dispatch:  # Allows manual trigger from GitHub UI

permissions:
  contents: write
  issues: write    # For creating issues on failure

jobs:
  update-website:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Update Website
      id: update
      run: |
        try {
          # Get current date in desired format
          $current_date = Get-Date -Format "yyyy-MM-dd"
          
          # Read current version from version.py
          $version = Get-Content lib/version.py | Select-String -Pattern "__version__ = ""([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)""" | ForEach-Object { $_.Matches.Groups[1].Value }
          if (-not $version) {
              throw "Could not read version from version.py"
          }
          
          # Read the HTML file
          $html_path = "releases/website/index.html"
          $content = Get-Content $html_path -Raw
          
          # Replace version and date placeholders
          $content = $content -replace "v__VERSION__", "v$version"
          $content = $content -replace "__DATE__", "$current_date"
          
          # Write updated content back to file
          Set-Content $html_path $content -NoNewline
          
          echo "::set-output name=status::success"
        } catch {
          echo "::set-output name=status::failed"
          echo "::error::$_"
          exit 1
        }
      shell: pwsh

    # Optional: Add notification on failure
    - name: Notify on failure
      if: failure()
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'Website update failed',
            body: 'The website update workflow failed. Please check the Actions tab for details.'
          })
    
    - name: Commit website changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add releases/website/index.html
        git commit -m "Update website with current version and date"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git push
      shell: pwsh